- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/bo/Auction.java
- src/main/java/fr/eni/tp/encheres/bo/Category.java
- src/main/java/fr/eni/tp/encheres/bo/PickupLocation.java
- src/main/java/fr/eni/tp/encheres/bo/User.java
> création des classes POJO pour la BO

- src/main/java/fr/eni/tp/encheres/configuration/security/SecurityConfig.java
- src/main/java/fr/eni/tp/encheres/controller/AuctionController.java
- src/main/resources/static/css/article-create.css
- src/main/resources/static/css/auctions.css
- src/main/resources/static/css/general.css
- src/main/resources/templates/article-create.html
- src/main/resources/templates/auctions.html
- src/main/resources/templates/fragments/fragment-footer.html
- src/main/resources/templates/fragments/fragment-header.html
- src/main/resources/templates/index.html
Création de la page des enchères et de la création d'un article avec style associé.
Création des entêtes et footer avec style général.
Les champs sont en durs et devront être modifié avec Thymeleaf plus tard.
Modification de LoginController pour la redirection.
Création de AuctionController pour la navigation entre les pages créées. 
Ajout de règles de navigation dans SecurityConfig.
> Création pages & navigation

- src/main/java/fr/eni/tp/encheres/bll/AuctionService.java
- src/main/java/fr/eni/tp/encheres/bll/UserService.java
- src/main/java/fr/eni/tp/encheres/bll/utilisateurService.java
- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/bo/Auction.java
- src/main/java/fr/eni/tp/encheres/bo/Category.java
- src/main/java/fr/eni/tp/encheres/bo/User.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAO.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAO.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/CategoryDAO.java
- src/main/java/fr/eni/tp/encheres/dal/CategoryDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAO.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/articleDAO.java
- src/main/java/fr/eni/tp/encheres/dal/enchereDAO.java
- src/test/java/fr/eni/tp/encheres/dal/TestAuctionDaoImpl.java
Update UserDAO et CategoryDAO + Create UserDAOImpl et CategoryDAOImpl
> Create UserDAOImpl et CategoryDAOImpl

- src/main/java/fr/eni/tp/encheres/controller/LoginController.java
- src/main/resources/static/css/article-create.css
- src/main/resources/static/css/signup.css
- src/main/resources/templates/article-create.html
- src/main/resources/templates/auctions.html
- src/main/resources/templates/signup.html
Création de la page d'inscription 'signup.html' et style associé.
Modification de LoginController pour pouvoir y accéder. 
Modification de 'article-create' pour y ajouter le champ de l'horaire (heures/minutes).
> Page d'inscription et petites modifs

- src/main/java/fr/eni/tp/encheres/configuration/security/SecurityConfig.java
- src/main/java/fr/eni/tp/encheres/controller/LoginController.java
- src/main/resources/static/css/login.css
- src/main/resources/templates/login.html
Modification SecurityConfig 
Modification LoginController
Ajout login.html
Ajout login.css
voir Notion : https://www.notion.so/Se-connecter-fe365f320c3b48219522d72f266cfa98?pvs=4
> ajout page html css login et modif security et login

- src/main/java/fr/eni/tp/encheres/bll/AuctionService.java
- src/main/java/fr/eni/tp/encheres/bll/AuctionServiceImpl.java
- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/bo/Category.java
- src/main/java/fr/eni/tp/encheres/bo/User.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAO.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAO.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/PickUpLocationDAO.java
- src/main/java/fr/eni/tp/encheres/dal/PickUpLocationDAOImpl.java
début de la BLL avec  création de AuctionService
> AuctionService

- src/main/java/fr/eni/tp/encheres/bo/User.java
- src/main/java/fr/eni/tp/encheres/configuration/security/SecurityConfig.java
- src/main/java/fr/eni/tp/encheres/controller/LoginController.java
- src/main/resources/templates/article-create.html
- src/main/resources/templates/auctions.html
- src/main/resources/templates/login.html
- src/main/resources/templates/signup.html
Légères modifs sur les pages car oublis, modifications de 'signup' avec Thymeleaf.
Récupération des données du formulaire dans LoginController.
Ajout de l'attribut 'passwordConfirm' dans User.
> Légères modifs et récupération des données du formulaire d'inscription

- src/main/java/fr/eni/tp/encheres/controller/LoginController.java
- src/main/java/fr/eni/tp/encheres/controller/ProfilController.java
- src/main/resources/templates/article-create.html
Ajout de l'utilisateur en session sur ProfilController pour pouvoir accéder aux attributs de l'utilisateur connecté (et afficher ses infos sur le /profil).
Utilisation de cet utilisateur en session pour mettre l'adresse de retrait par défaut.
> User session et adress de retrait par défaut

- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/bo/PickupLocation.java
- src/main/java/fr/eni/tp/encheres/controller/AuctionController.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAOImpl.java
- src/main/resources/templates/article-create.html
- src/main/resources/templates/auctions.html
Formulaire création article avec Thymeleaf, récupération des champs dans le controller et mise en BDD (ATTENTION AUCUNE VERIFICATIONS/VALIDATIONS DE FAITES). 
Ajout d'attributs dans Article pour gérer les inputs date et time. 
Modification du RowMapper en conséquence. 
Refacto finalPrice -> currentPrice, getters,setters et utilisations dans les pages html aussi. 
Constructeur avec champs dans PickupLocation
> Création d'article du formulaire à la BDD (sans validations)

- src/main/java/fr/eni/tp/encheres/bll/AuctionService.java
- src/main/java/fr/eni/tp/encheres/bll/AuctionServiceImpl.java
- src/main/java/fr/eni/tp/encheres/controller/AuctionController.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAO.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAOImpl.java
- src/main/resources/templates/auctions.html
Fonctionne uniquement pour les ventes que l'utilisateur a en cours.
> sélection des ventes de l'utilisateur connecté

- src/main/resources/static/css/article-create.css
- src/main/resources/static/css/auctions.css
- src/main/resources/static/css/general.css
- src/main/resources/static/css/login.css
- src/main/resources/static/css/profil.css
- src/main/resources/static/css/signup.css
- src/main/resources/static/js/navbar.js
- src/main/resources/templates/article-create.html
- src/main/resources/templates/fragments/fragment-header.html
- src/main/resources/templates/signup.html
Modif article-create.css
Modif auctions.css
Modif general.css
Modif login.css
Modif signup.css
Modif article-create.html
Modif header
Modif signup.html
Ajout js & navbar.js
> Modification css

- src/main/java/fr/eni/tp/encheres/bll/UserService.java
- src/main/java/fr/eni/tp/encheres/bll/UserServiceImpl.java
- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/controller/AuctionController.java
- src/main/java/fr/eni/tp/encheres/controller/LoginController.java
- src/main/java/fr/eni/tp/encheres/controller/ProfilController.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAO.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAOImpl.java
- src/main/resources/static/css/profil.css
- src/main/resources/static/css/signup.css
- src/main/resources/templates/article-create.html
- src/main/resources/templates/profil-modify.html
- src/main/resources/templates/profil.html
Affichage du profil avec les détails de l'utilisateur connecté. 
Création de la page 'profil-modify.html' avec méthode GET/POST dans ProfilController associé. 
Écriture en base de donnée du profil modifié avec check sur la disponibilité de l'email et du pseudo.
Création des requêtes pour check la dispo de l'email et du pseudo dans UserDAO/UserDAOImpl.
Création de quelques méthodes dans UserService/UserServiceImpl pour la validation des modifications d'un utilisateur.
Création de fillUserAttributes pour refacto du code.
Modifications du formulaire ET de la classe Article en enlevant les attributs inutiles (LocalDate/LocalTime).
> Affichage Profil + Modif Profil (sauf MDP) + Refacto général

- src/main/java/fr/eni/tp/encheres/bll/UserService.java
- src/main/java/fr/eni/tp/encheres/bll/UserServiceImpl.java
- src/main/java/fr/eni/tp/encheres/controller/ProfilController.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAO.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAOImpl.java
- src/main/resources/templates/profil-modify.html
Ajout des vérifications sur le changement de mot de passe, verif mot de passe actuel et l'égalité entre le nouveau et la confirmation. Gestion en System.out des 'erreurs'.
Pas de vérifications sur les autres champs ou sur la forme du mot de passe (caractères spéciaux, majuscules, etc ...)
Le changement de mot de passe fonctionne bien en BDD et pour la connexion.
> Modification mot de passe OK

- src/main/java/fr/eni/tp/encheres/bll/UserService.java
- src/main/java/fr/eni/tp/encheres/bll/UserServiceImpl.java
- src/main/java/fr/eni/tp/encheres/controller/ProfilController.java
- src/main/resources/templates/fragments/fragment-header.html
- src/main/resources/templates/profil.html
Modification affichage profil avec l'id en paramètre url, permet l'affichage de n'importe quel profil si on est connecté. Correction par conséquences des liens d'affichage de profil pour y glisser l'id (navbar et auctions).
> Changement affichage des profils, avec un id en paramètre url

- src/main/java/fr/eni/tp/encheres/controller/PaperCutEmailController.java
- src/main/resources/templates/forgot-password.html
Création de la page HTML et du controller pour réinitialiser le mot de passe
> Création de la page de réinit MP

- src/main/java/fr/eni/tp/encheres/bll/AuctionServiceImpl.java
- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/controller/BidController.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAO.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAO.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAOImpl.java
- src/main/resources/static/css/bid-article-detail.css
- src/main/resources/templates/auctions.html
- src/main/resources/templates/bid-article-detail.html
Page HTML / CSS 'bid-article-detail' avec les infos de l'article en vente.
Possibilité de faire une enchère sous condition temporelle (entre le début et la fin de l'enchère).
Affichage conditionnel de la future zone pour aller modifier l'article quand c'est encore possible (avant le début pour modification des attributs, et pendant pour supprimer la vente).
Récupération de la mise/montant dans BidController, envoi dans la BLL qui vérifie la validité des champs (montant supérieur au précédent et date avant celle de fin).
Création de requêtes pour update un article en BDD (prix_vente ET no_acheteur).
Refacto dans Auction : buyer -> currentBuyer (getters et setters associés).
ATTENTION MODIF DANS LE SCRIPT DE LA BASE DE DONNÉES.
DONC MODIF A FAIRE DES AUTRES REQUETES de ArticleDAOImpl.
> Création d'une enchère et écriture en BDD

- src/main/java/fr/eni/tp/encheres/bll/AuctionServiceImpl.java
- src/main/java/fr/eni/tp/encheres/bll/UserService.java
- src/main/java/fr/eni/tp/encheres/bll/UserServiceImpl.java
- src/main/java/fr/eni/tp/encheres/controller/LoginController.java
- src/main/java/fr/eni/tp/encheres/controller/ProfilController.java
- src/main/resources/templates/login.html
- src/main/resources/templates/profil-modify.html
- src/main/resources/templates/signup.html
Finalisation de la validation avec ajout des messages d'erreur aux templates.
Restera à gérer le CSS.
> Validation

- src/main/java/fr/eni/tp/encheres/bll/AuctionService.java
- src/main/java/fr/eni/tp/encheres/bll/AuctionServiceImpl.java
- src/main/java/fr/eni/tp/encheres/bll/UserService.java
- src/main/java/fr/eni/tp/encheres/bll/UserServiceImpl.java
- src/main/java/fr/eni/tp/encheres/bo/Article.java
- src/main/java/fr/eni/tp/encheres/controller/AuctionController.java
- src/main/java/fr/eni/tp/encheres/controller/BidController.java
- src/main/java/fr/eni/tp/encheres/dal/ArticleDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/PickUpLocationDAO.java
- src/main/java/fr/eni/tp/encheres/dal/PickUpLocationDAOImpl.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAO.java
- src/main/java/fr/eni/tp/encheres/dal/UserDAOImpl.java
- src/main/resources/static/css/bid-article-detail.css
- src/main/resources/templates/article-modify.html
- src/main/resources/templates/bid-article-detail.html
Refactoring et modif de la classe article (enlever la liste d'enchères car boucle infinie).
Gestion des enchères, écriture en base de donnée si condition ok (assez de crédit, date ok, montant supérieur au précédent).
Modification des crédits des utilisateurs concernés en BDD.
Modification d'un article avant le début des enchères OK.
Mise en commentaires des System.out de débug.
ATTENTION, il y a encore des boucles rétroactives entre nos classes (Article qui stocke des Users, User qui stocke des Auctions, Auction qui stocke un Article OU User qui stocke des Articles, Article qui stocke des Users DONC des comportements bizarres à prévoir/prévenir/envisager.
PS : Les majs c'est pas parce que je suis énervé :)
> Refacto de ArticleDAOImpl+enchérir sur un article OK+modifier un article avant le début des enchères OK

- src/main/java/fr/eni/tp/encheres/bo/Auction.java
- src/main/java/fr/eni/tp/encheres/controller/BidController.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAOImpl.java
- src/main/resources/static/css/bid-article-detail.css
- src/main/resources/templates/article-create.html
- src/main/resources/templates/bid-article-detail.html
HMTL et Style.
Récup des enchères lié à un article.
Affichage conditionnel (si l'utilisateur connecté est bien le vendeur)
Nouvel attribut formatedDate dans Auction pour l'affichage.
Affection de cet attribut directement dans la DAL à la récupération depuis la BDD.
> Affichage des enchérisseur

- src/main/resources/static/css/general.css
- src/main/resources/templates/error.html
- src/main/resources/templates/fragments/fragment-clean-header.html
Style minimal erreurs.
Style error.html.
Nouvelle entête sans faire appel à userSession.
> Style erreurs et page d'erreur. Nouvelle entête pour error.html

- src/main/java/fr/eni/tp/encheres/bo/Auction.java
- src/main/java/fr/eni/tp/encheres/dal/AuctionDAOImpl.java
- src/main/resources/templates/bid-article-detail.html
- src/main/resources/templates/error.html
Modif Auction en enlevant l'attribut formatedDate
Formatage en Thymeleaf direct.
Changement redirect de error.html à "/session" pour avoir un user vide en session.
> Auction et error.html modifs

- src/main/java/fr/eni/tp/encheres/controller/AuctionController.java
- src/main/resources/language/messages.properties
- src/main/resources/language/messages_en.properties
- src/main/resources/templates/article-modify.html
avec ajout d'un message en tête de la page pour expliquer
> suppression du bouton modifier l'article pour les ventes débutées
